// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: proto/control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 节点基本信息
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                                             // 节点唯一ID
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                                                                       // 主机名
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`                                                    // IP地址
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`                                                                         // Agent版本
	Uptime        int64                  `protobuf:"varint,5,opt,name=uptime,proto3" json:"uptime,omitempty"`                                                                          // 运行时间（秒）
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 标签（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeInfo) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *NodeInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ControlToken  string                 `protobuf:"bytes,3,opt,name=control_token,json=controlToken,proto3" json:"control_token,omitempty"` // 控制端认证令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetControlToken() string {
	if x != nil {
		return x.ControlToken
	}
	return ""
}

// 心跳请求（Agent -> Control）
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Health        *NodeHealth            `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"` // 节点健康状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetHealth() *NodeHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

// 心跳响应（Control -> Agent）
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Alive         bool                   `protobuf:"varint,3,opt,name=alive,proto3" json:"alive,omitempty"`                                      // 是否存活
	NextHeartbeat int64                  `protobuf:"varint,4,opt,name=next_heartbeat,json=nextHeartbeat,proto3" json:"next_heartbeat,omitempty"` // 下次心跳间隔（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetNextHeartbeat() int64 {
	if x != nil {
		return x.NextHeartbeat
	}
	return 0
}

// 节点健康状态
type NodeHealth struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent        int64                  `protobuf:"varint,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`                      // CPU使用率
	MemoryPercent     int64                  `protobuf:"varint,2,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`             // 内存使用率
	DiskPercent       int64                  `protobuf:"varint,3,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`                   // 磁盘使用率
	ActiveConnections int32                  `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"` // 活跃连接数
	NetworkRx         float64                `protobuf:"fixed64,5,opt,name=network_rx,json=networkRx,proto3" json:"network_rx,omitempty"`                        // 网络接收（KB/s）
	NetworkTx         float64                `protobuf:"fixed64,6,opt,name=network_tx,json=networkTx,proto3" json:"network_tx,omitempty"`                        // 网络发送（KB/s）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeHealth) Reset() {
	*x = NodeHealth{}
	mi := &file_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealth) ProtoMessage() {}

func (x *NodeHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealth.ProtoReflect.Descriptor instead.
func (*NodeHealth) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{4}
}

func (x *NodeHealth) GetCpuPercent() int64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeHealth) GetMemoryPercent() int64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *NodeHealth) GetDiskPercent() int64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *NodeHealth) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *NodeHealth) GetNetworkRx() float64 {
	if x != nil {
		return x.NetworkRx
	}
	return 0
}

func (x *NodeHealth) GetNetworkTx() float64 {
	if x != nil {
		return x.NetworkTx
	}
	return 0
}

// 配置请求（Control -> Agent）
type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RequestType   string                 `protobuf:"bytes,2,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"` // "get", "update", "delete"
	Config        *ProxyConfig           `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`                              // 代理配置（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_proto_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ConfigRequest) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *ConfigRequest) GetConfig() *ProxyConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// 配置更新（Agent -> Control）
type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Configs       []*ProxyConfig         `protobuf:"bytes,4,rep,name=configs,proto3" json:"configs,omitempty"` // 当前运行的代理配置列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_proto_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ConfigUpdate) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigUpdate) GetConfigs() []*ProxyConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

// 代理配置
type ProxyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OutboundType  string                 `protobuf:"bytes,3,opt,name=outbound_type,json=outboundType,proto3" json:"outbound_type,omitempty"`                                           // "hysteria2", "vmess", "socks5"
	InboundPort   int32                  `protobuf:"varint,4,opt,name=inbound_port,json=inboundPort,proto3" json:"inbound_port,omitempty"`                                             // 入站端口
	TargetServer  string                 `protobuf:"bytes,5,opt,name=target_server,json=targetServer,proto3" json:"target_server,omitempty"`                                           // 目标服务器
	TargetPort    int32                  `protobuf:"varint,6,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`                                                // 目标端口
	Params        map[string]string      `protobuf:"bytes,7,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 其他参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyConfig) Reset() {
	*x = ProxyConfig{}
	mi := &file_proto_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConfig) ProtoMessage() {}

func (x *ProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConfig.ProtoReflect.Descriptor instead.
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{7}
}

func (x *ProxyConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProxyConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProxyConfig) GetOutboundType() string {
	if x != nil {
		return x.OutboundType
	}
	return ""
}

func (x *ProxyConfig) GetInboundPort() int32 {
	if x != nil {
		return x.InboundPort
	}
	return 0
}

func (x *ProxyConfig) GetTargetServer() string {
	if x != nil {
		return x.TargetServer
	}
	return ""
}

func (x *ProxyConfig) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *ProxyConfig) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// 节点状态上报（Agent -> Control）
type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Health        *NodeHealth            `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	Proxies       []*ProxyStatus         `protobuf:"bytes,4,rep,name=proxies,proto3" json:"proxies,omitempty"` // 代理状态列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_proto_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{8}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NodeStatus) GetHealth() *NodeHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *NodeStatus) GetProxies() []*ProxyStatus {
	if x != nil {
		return x.Proxies
	}
	return nil
}

// 代理运行状态
type ProxyStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Running           bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`                                              // 是否运行中
	Uptime            int64                  `protobuf:"varint,4,opt,name=uptime,proto3" json:"uptime,omitempty"`                                                // 运行时间（秒）
	TotalBytes        int64                  `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`                      // 总流量（字节）
	ActiveConnections int32                  `protobuf:"varint,6,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"` // 活跃连接数
	ErrorMessage      string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                 // 错误信息（如果有）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProxyStatus) Reset() {
	*x = ProxyStatus{}
	mi := &file_proto_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyStatus) ProtoMessage() {}

func (x *ProxyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyStatus.ProtoReflect.Descriptor instead.
func (*ProxyStatus) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{9}
}

func (x *ProxyStatus) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProxyStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProxyStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ProxyStatus) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *ProxyStatus) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *ProxyStatus) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *ProxyStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 状态响应（Control -> Agent）
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // 推荐的操作：none, restart, update_config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{10}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_proto_control_proto protoreflect.FileDescriptor

const file_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x13proto/control.proto\x12\acontrol\"\x82\x02\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\x03R\x06uptime\x125\n" +
	"\x06labels\x18\x06 \x03(\v2\x1d.control.NodeInfo.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rcontrol_token\x18\x03 \x01(\tR\fcontrolToken\"v\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12+\n" +
	"\x06health\x18\x03 \x01(\v2\x13.control.NodeHealthR\x06health\"\x87\x01\n" +
	"\x11HeartbeatResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05alive\x18\x03 \x01(\bR\x05alive\x12%\n" +
	"\x0enext_heartbeat\x18\x04 \x01(\x03R\rnextHeartbeat\"\xe4\x01\n" +
	"\n" +
	"NodeHealth\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x03R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x02 \x01(\x03R\rmemoryPercent\x12!\n" +
	"\fdisk_percent\x18\x03 \x01(\x03R\vdiskPercent\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x05R\x11activeConnections\x12\x1d\n" +
	"\n" +
	"network_rx\x18\x05 \x01(\x01R\tnetworkRx\x12\x1d\n" +
	"\n" +
	"network_tx\x18\x06 \x01(\x01R\tnetworkTx\"y\n" +
	"\rConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\frequest_type\x18\x02 \x01(\tR\vrequestType\x12,\n" +
	"\x06config\x18\x03 \x01(\v2\x14.control.ProxyConfigR\x06config\"\x8b\x01\n" +
	"\fConfigUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12.\n" +
	"\aconfigs\x18\x04 \x03(\v2\x14.control.ProxyConfigR\aconfigs\"\xb4\x02\n" +
	"\vProxyConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\routbound_type\x18\x03 \x01(\tR\foutboundType\x12!\n" +
	"\finbound_port\x18\x04 \x01(\x05R\vinboundPort\x12#\n" +
	"\rtarget_server\x18\x05 \x01(\tR\ftargetServer\x12\x1f\n" +
	"\vtarget_port\x18\x06 \x01(\x05R\n" +
	"targetPort\x128\n" +
	"\x06params\x18\a \x03(\v2 .control.ProxyConfig.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12+\n" +
	"\x06health\x18\x03 \x01(\v2\x13.control.NodeHealthR\x06health\x12.\n" +
	"\aproxies\x18\x04 \x03(\v2\x14.control.ProxyStatusR\aproxies\"\xd8\x01\n" +
	"\vProxyStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\x03R\x06uptime\x12\x1f\n" +
	"\vtotal_bytes\x18\x05 \x01(\x03R\n" +
	"totalBytes\x12-\n" +
	"\x12active_connections\x18\x06 \x01(\x05R\x11activeConnections\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"\\\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action2\x97\x02\n" +
	"\x0eControlService\x12<\n" +
	"\fRegisterNode\x12\x11.control.NodeInfo\x1a\x19.control.RegisterResponse\x12F\n" +
	"\tHeartbeat\x12\x19.control.HeartbeatRequest\x1a\x1a.control.HeartbeatResponse(\x010\x01\x12A\n" +
	"\fStreamConfig\x12\x16.control.ConfigRequest\x1a\x15.control.ConfigUpdate(\x010\x01\x12<\n" +
	"\fReportStatus\x12\x13.control.NodeStatus\x1a\x17.control.StatusResponseB\x13Z\x11goForward/controlb\x06proto3"

var (
	file_proto_control_proto_rawDescOnce sync.Once
	file_proto_control_proto_rawDescData []byte
)

func file_proto_control_proto_rawDescGZIP() []byte {
	file_proto_control_proto_rawDescOnce.Do(func() {
		file_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)))
	})
	return file_proto_control_proto_rawDescData
}

var file_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_control_proto_goTypes = []any{
	(*NodeInfo)(nil),          // 0: control.NodeInfo
	(*RegisterResponse)(nil),  // 1: control.RegisterResponse
	(*HeartbeatRequest)(nil),  // 2: control.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: control.HeartbeatResponse
	(*NodeHealth)(nil),        // 4: control.NodeHealth
	(*ConfigRequest)(nil),     // 5: control.ConfigRequest
	(*ConfigUpdate)(nil),      // 6: control.ConfigUpdate
	(*ProxyConfig)(nil),       // 7: control.ProxyConfig
	(*NodeStatus)(nil),        // 8: control.NodeStatus
	(*ProxyStatus)(nil),       // 9: control.ProxyStatus
	(*StatusResponse)(nil),    // 10: control.StatusResponse
	nil,                       // 11: control.NodeInfo.LabelsEntry
	nil,                       // 12: control.ProxyConfig.ParamsEntry
}
var file_proto_control_proto_depIdxs = []int32{
	11, // 0: control.NodeInfo.labels:type_name -> control.NodeInfo.LabelsEntry
	4,  // 1: control.HeartbeatRequest.health:type_name -> control.NodeHealth
	7,  // 2: control.ConfigRequest.config:type_name -> control.ProxyConfig
	7,  // 3: control.ConfigUpdate.configs:type_name -> control.ProxyConfig
	12, // 4: control.ProxyConfig.params:type_name -> control.ProxyConfig.ParamsEntry
	4,  // 5: control.NodeStatus.health:type_name -> control.NodeHealth
	9,  // 6: control.NodeStatus.proxies:type_name -> control.ProxyStatus
	0,  // 7: control.ControlService.RegisterNode:input_type -> control.NodeInfo
	2,  // 8: control.ControlService.Heartbeat:input_type -> control.HeartbeatRequest
	5,  // 9: control.ControlService.StreamConfig:input_type -> control.ConfigRequest
	8,  // 10: control.ControlService.ReportStatus:input_type -> control.NodeStatus
	1,  // 11: control.ControlService.RegisterNode:output_type -> control.RegisterResponse
	3,  // 12: control.ControlService.Heartbeat:output_type -> control.HeartbeatResponse
	6,  // 13: control.ControlService.StreamConfig:output_type -> control.ConfigUpdate
	10, // 14: control.ControlService.ReportStatus:output_type -> control.StatusResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_control_proto_init() }
func file_proto_control_proto_init() {
	if File_proto_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_proto_goTypes,
		DependencyIndexes: file_proto_control_proto_depIdxs,
		MessageInfos:      file_proto_control_proto_msgTypes,
	}.Build()
	File_proto_control_proto = out.File
	file_proto_control_proto_goTypes = nil
	file_proto_control_proto_depIdxs = nil
}
